# Generated by Django 4.0.1 on 2022-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('Detective', 'Detective'), ('Comedy', 'Comedy'), ('History', 'History'), ('Fantasy', 'Fantasy'), ('SelfEducation', 'SelfEducation'), ('Classic', 'Classic')], max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
